apiVersion: v1
kind: Service
metadata:
  name: es-cluster
  labels:
    service: elasticsearch
spec:
  clusterIP: None
  ports:
  - port: 9200
    name: serving
  - port: 9300
    name: node-to-node
  selector:
    service: elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  name: es-endpoint
  labels:
    service: elasticsearch
  annotations:
    cloud.google.com/load-balancer-type: Internal
spec:
  type: LoadBalancer
  selector:
    service: elasticsearch
  ports:
  - protocol: TCP
    port: 9200